### ISSUE TITLE
missing `debug` dependency in package.json

### ISSUE THREAD

**Issue by macrozone** [Kikobeats/debug-logfmt#3]
for the upcoming yarn2 and propably more future packager, its nessesary that every module specifies all their dependencies.

see https://yarnpkg.com/advanced/migration#a-package-is-trying-to-access-another-package-

this package uses `debug@^4` from `debug-fabulous`

**Comment by Kikobeats** [comment]
then it's not missing, it's installed since it's a dependency of a dependency

https://github.com/nmccready/debug-fabulous/blob/master/package.json#L43

**Comment by macrozone** [comment]
> then it's not missing, it's installed since it's a dependency of a dependency
> 
> https://github.com/nmccready/debug-fabulous/blob/master/package.json#L43

that is the point. If you access indirect dependencies, you should list them in package.json: https://yarnpkg.com/advanced/migration#a-package-is-trying-to-access-another-package-

**Comment by Kikobeats** [comment]
Definitely I'm not living in the edge and I have no idea how Yarn v2, but not sure how helpful is a package manager that can't infer dependencies from sub dependencies.

Probably because https://next.yarnpkg.com/features/pnp ?

Does this explain why some big players (like Facebook) to use Yarn v2 and stay at Yarn v1 aka "classic"?

Just asking with all the curiosity from a non regular yarn user

**Comment by macrozone** [comment]
@Kikobeats it can infer dependencies from sub dependencies, but using dependencies of dependencies without declaring that transitive dependency isn't a good practice anyway, it even leads to linting errors usually. Imaging if you update dependency A and it no longer declares dependency on B, but you require B. Now you will get an error. 

Now, "plug & play" should replace the classic node_modules approach to fix some problems with it (size, slow start) and enables zero-install repositories. it also enforces stronger boundaries between dependencies, so that using dependencies of other dependencies without declaring them is not possible.

the reason why facebook will stay at v1 for the time beeing is because they have a ton of projects and some of them have custom built tools which sometimes rely on the node_modues folder. A famous one is react-native which needs node_modules, e.g. the generated xcode or android link their libraries from the node_modules folder.
